# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='nombre_tabla',
            field=models.CharField(default='', max_length=100),
        ),
    ]
